### ISSUE TITLE
Raise warning when no run IDs are linked to aggregate ID

### ISSUE THREAD

**Issue by adamovanja** [bokulich-lab/q2-fondue#137]
As a plugin user, 
I want `get-metadata` to return a warning or a Q2 error in case one aggregate ID (e.g. BioProject ID, Study ID) of many has no linked run ID entires in the SRA database. 

**Steps to reproduce:**
* Run `get-metadata` with an input artifact containing the following accession IDs within: `PRJNA290381` & `PRJNA18197`.

**Current behaviour:**
`get-metadata` exits with an empty SRAFailedIDs artifact and the output `SRAMetadata` only containing metadata of the second accession ID `PRJNA18197` and no information on the first accession ID (`PRJNA290381`) for which no run IDs are linked in the SRA:
```
2022-08-08 11:06:18,718 [MainThread] [INFO] [entrezpy.conduit.Conduit]: {"querying": {"queryid": "nENHoXsWTd2Q0XdxXQDDSw==", "util": "esearch"}}
2022-08-08 11:06:20,730 [MainThread] [INFO] [entrezpy.conduit.Conduit]: {"querying": {"queryid": "Vq23ZxROQs26_xhKiBLZ1A==", "util": "elink"}}
2022-08-08 11:06:22,740 [MainThread] [INFO] [entrezpy.conduit.Conduit]: {"querying": {"queryid": "vw0N_jJNRoWqb8s_k-2zRA==", "util": "efetch"}}
2022-08-08 11:06:23,747 [MainThread] [INFO] [q2_fondue.metadata]: Fetching metadata for 4 run IDs.
Saved SRAMetadata to: diab_fail/metadata.qza
Saved SRAFailedIDs to: diab_fail/failed_runs.qza
```

**Expected behaviour:**
A warning or an error should be raised in case the run IDs of one aggregate ID could not be fetched (by `q2_fondue.entrezpy_clients._pipelines._get_run_ids`).

**Comment by valentynbez** [comment]
The same verbose error is needed in the case of `get-ids-from-query` function. 
Current behaviour: 
- Study: `PRJNA688998` - no IDs on SRA

```sh
qiime fondue get-ids-from-query \
--p-query "PRJNA688998[All fields]" \
--p-email email.com \
--p-n-jobs 8 \
--o-ids test_ids.qza \
--verbose
```

```
2023-01-21 11:35:09,266 [Thread-3] [ERROR] [ThreadedErrorsManager]: Data fetching was interrupted by the following error:
Caught <class 'TypeError'> with value "'NoneType' object is not iterable" in thread <ThreadedRequester(Thread-3, started daemon 139898786801408)>
Traceback (most recent call last):
  File "/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/vbezshapkin/conda-envs/qiime2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/vbezshapkin/conda-envs/qiime2/lib/python3.8/site-packages/entrezpy/requester/threadedrequest.py", line 48, in run
    self.run_one_request(request, analyzer)
  File "/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/vbezshapkin/conda-envs/qiime2/lib/python3.8/site-packages/entrezpy/requester/threadedrequest.py", line 71, in run_one_request
    analyzer.parse(response, request)
  File "/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/vbezshapkin/conda-envs/qiime2/lib/python3.8/site-packages/entrezpy/base/analyzer.py", line 117, in parse
    self.analyze_result(response, request)
  File "/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/vbezshapkin/conda-envs/qiime2/lib/python3.8/site-packages/q2_fondue/entrezpy_clients/_esearch.py", line 105, in analyze_result
    self.result.parse_search_results(response, self.uids)
  File "/nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/vbezshapkin/conda-envs/qiime2/lib/python3.8/site-packages/q2_fondue/entrezpy_clients/_esearch.py", line 71, in parse_search_results
    self.result = pd.Series({x: 0 for x in uids}, name='count')
TypeError: 'NoneType' object is not iterable
```

**Comment by valentynbez** [comment]
Hi, 

I inspected the error further and yes, it is a separate issue. Sorry.
